language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - ca-certificates

install: "pip install -r requirements.txt"

script:
  - echo "Unit tests"

after_script:

  # start the web app
  - |
    python app.py &
    APP_PID=$!


  # execute the API tests
  #
  - |
    pytest -v test_flask.py
        
  - kill $APP_PID