machine:
  python:
    version: 3.5.2


dependencies:
  override:
    - pip install -r requirements.txt

- run:
      name: Run Servers
      command: python app.py
      background: true    

test:
  override:
    - nosetests test_flask.py
