machine:
  python:
    version: 3.5.2


dependencies:
  override:
    - pip install -r requirements.txt

- run:
      name: Run Servers
      command: python app.py
      background: true    
- run:
      name: Run Servers
      command: nosetests test_flask.py
      
